name: Lint shared workflows

on:
  push:

jobs:
  lint:
    name: Lint shared workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Workflows
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_GITHUB_ACTIONS: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
